plugins:
  - jekyll-sitemap

# SEO Stuff
author: Tony Cavella
description: automation, infrastructure, security
lang: en
locale: en_GB
url: "https://cavella.com"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20
